export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING';
export const RESERVATIONS_FAILED  = 'RESERVATIONS_FAILED';
export const ADD_RESERVATIONS     = 'ADD_RESERVATIONS';
export const ADD_RESERVATION      = 'ADD_RESERVATION';